"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_redux_1 = require("react-redux");
var ContactUs = /** @class */ (function (_super) {
    __extends(ContactUs, _super);
    function ContactUs() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    ContactUs.prototype.render = function () {
        return (React.createElement(React.Fragment, null,
            React.createElement("div", { className: "hotale-page-title-wrap  hotale-style-custom hotale-center-align" },
                React.createElement("div", { className: "hotale-header-transparent-substitute", style: { height: "149.3px" } }),
                React.createElement("div", { className: "hotale-page-title-overlay" }),
                React.createElement("div", { className: "hotale-page-title-container hotale-container" },
                    React.createElement("div", { className: "hotale-page-title-content hotale-item-pdlr" },
                        React.createElement("h1", { className: "hotale-page-title" }, "Haqq\u0131m\u0131zda")))),
            " ",
            React.createElement("div", { className: "gdlr-core-pbf-wrapper ", style: { padding: "30px 0px 20px 0px" }, "data-skin": "White Text" },
                React.createElement("div", { className: "gdlr-core-pbf-background-wrap", style: { backgroundColor: "#191919" } },
                    React.createElement("div", { className: "gdlr-core-pbf-background gdlr-core-parallax gdlr-core-js", style: {
                            opacity: "0.5",
                            backgroundSize: "cover",
                            backgroundPosition: "center center",
                            height: "420.12px",
                            transform: "translate(0px, -64.3px)",
                        }, "data-parallax-speed": "0.2" })),
                React.createElement("div", { className: "gdlr-core-pbf-wrapper-content gdlr-core-js " },
                    React.createElement("div", { className: "gdlr-core-pbf-wrapper-container clearfix gdlr-core-container" },
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-20 gdlr-core-column-first", id: "gdlr-core-column-1" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "50px 20px 0px 20px" } },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js", "data-gdlr-animation-duration": "600ms", "data-gdlr-animation-offset": "0.8", style: {} },
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-icon-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align", style: { paddingBottom: "40px" } },
                                            React.createElement("div", { className: " gdlr-core-icon-item-wrap gdlr-core-skin-e-background gdlr-core-icon-item-type-round", style: {
                                                    backgroundColor: "#ffffff",
                                                    borderRadius: "40px",
                                                    MozBorderRadius: "40px",
                                                    WebkitBorderRadius: "40px",
                                                    padding: "20px 20px 20px 20px",
                                                } },
                                                React.createElement("i", { className: " gdlr-core-icon-item-icon fa fa-phone gdlr-core-skin-e-content", style: {
                                                        color: "#0a0a0a",
                                                        fontSize: "40px",
                                                        minWidth: "40px",
                                                        minHeight: "40px",
                                                    } })))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr", style: { paddingBottom: "25px" } },
                                            React.createElement("div", { className: "gdlr-core-title-item-title-wrap " },
                                                React.createElement("h3", { className: "gdlr-core-title-item-title gdlr-core-skin-title  class-test", style: {
                                                        fontSize: "26px",
                                                        letterSpacing: "0px",
                                                        textTransform: "none",
                                                        color: "#ffffff",
                                                    } },
                                                    "Phone",
                                                    React.createElement("span", { className: "gdlr-core-title-item-title-divider gdlr-core-skin-divider" }))))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align", style: { paddingBottom: "0px" } },
                                            React.createElement("div", { className: "gdlr-core-text-box-item-content", style: { textTransform: "none", color: "#ffffff" } },
                                                React.createElement("p", null, "A wonderful serenity has taken possession of my entire soul, like these.")))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align" },
                                            React.createElement("div", { className: "gdlr-core-text-box-item-content", style: { fontWeight: 700, textTransform: "none" } },
                                                React.createElement("p", null,
                                                    React.createElement("a", { style: { textDecoration: "underline" }, href: "#" }, "+1-2345-2345")))))))),
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-20", id: "gdlr-core-column-2" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "50px 20px 0px 20px" } },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js", "data-gdlr-animation-duration": "600ms", "data-gdlr-animation-offset": "0.8", style: {} },
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-icon-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align", style: { paddingBottom: "40px" } },
                                            React.createElement("div", { className: " gdlr-core-icon-item-wrap gdlr-core-skin-e-background gdlr-core-icon-item-type-round", style: {
                                                    backgroundColor: "#ffffff",
                                                    borderRadius: "40px",
                                                    MozBorderRadius: "40px",
                                                    WebkitBorderRadius: "40px",
                                                    padding: "24px 24px 24px 24px",
                                                } },
                                                React.createElement("i", { className: " gdlr-core-icon-item-icon fa fa-envelope-o gdlr-core-skin-e-content", style: {
                                                        color: "#000000",
                                                        fontSize: "31px",
                                                        minWidth: "31px",
                                                        minHeight: "31px",
                                                    } })))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr", style: { paddingBottom: "25px" } },
                                            React.createElement("div", { className: "gdlr-core-title-item-title-wrap " },
                                                React.createElement("h3", { className: "gdlr-core-title-item-title gdlr-core-skin-title  class-test", style: {
                                                        fontSize: "26px",
                                                        letterSpacing: "0px",
                                                        textTransform: "none",
                                                        color: "#ffffff",
                                                    } },
                                                    "Email",
                                                    React.createElement("span", { className: "gdlr-core-title-item-title-divider gdlr-core-skin-divider" }))))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align", style: { paddingBottom: "0px" } },
                                            React.createElement("div", { className: "gdlr-core-text-box-item-content", style: { textTransform: "none", color: "#ffffff" } },
                                                React.createElement("p", null, "A wonderful serenity has taken possession of my entire soul, like these.")))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align" },
                                            React.createElement("div", { className: "gdlr-core-text-box-item-content", style: { fontWeight: 700, textTransform: "none" } },
                                                React.createElement("p", null,
                                                    React.createElement("a", { style: { textDecoration: "underline" }, href: "#" }, "Contact@goodlayersthemes.com")))))))),
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-20", id: "gdlr-core-column-3" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "50px 20px 0px 20px" } },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js", "data-gdlr-animation-duration": "600ms", "data-gdlr-animation-offset": "0.8", style: {} },
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-icon-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align", style: { paddingBottom: "40px" } },
                                            React.createElement("div", { className: " gdlr-core-icon-item-wrap gdlr-core-skin-e-background gdlr-core-icon-item-type-round", style: {
                                                    backgroundColor: "#ffffff",
                                                    borderRadius: "40px",
                                                    MozBorderRadius: "40px",
                                                    WebkitBorderRadius: "40px",
                                                    padding: "24px 24px 24px 24px",
                                                } },
                                                React.createElement("i", { className: " gdlr-core-icon-item-icon fa fa-location-arrow gdlr-core-skin-e-content", style: {
                                                        color: "#000000",
                                                        fontSize: "31px",
                                                        minWidth: "31px",
                                                        minHeight: "31px",
                                                    } })))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr", style: { paddingBottom: "25px" } },
                                            React.createElement("div", { className: "gdlr-core-title-item-title-wrap " },
                                                React.createElement("h3", { className: "gdlr-core-title-item-title gdlr-core-skin-title  class-test", style: {
                                                        fontSize: "26px",
                                                        letterSpacing: "0px",
                                                        textTransform: "none",
                                                        color: "#ffffff",
                                                    } },
                                                    "Location",
                                                    React.createElement("span", { className: "gdlr-core-title-item-title-divider gdlr-core-skin-divider" }))))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align", style: { paddingBottom: "0px" } },
                                            React.createElement("div", { className: "gdlr-core-text-box-item-content", style: { textTransform: "none", color: "#ffffff" } },
                                                React.createElement("p", null,
                                                    "4 apt. Flawing Street. The Grand Avenue.",
                                                    React.createElement("br", null),
                                                    "Liverpool, UK 33342")))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align" },
                                            React.createElement("div", { className: "gdlr-core-text-box-item-content", style: { fontWeight: 700, textTransform: "none" } },
                                                React.createElement("p", null,
                                                    React.createElement("a", { style: { textDecoration: "underline" }, href: "#" }, "View On Google Map"))))))))))),
            ";",
            React.createElement("div", { className: "gdlr-core-pbf-wrapper ", style: { padding: "90px 0px 35px 0px" } },
                React.createElement("div", { className: "gdlr-core-pbf-background-wrap", style: { backgroundColor: "#ffffff" } }),
                React.createElement("div", { className: "gdlr-core-pbf-wrapper-content gdlr-core-js " },
                    React.createElement("div", { className: "gdlr-core-pbf-wrapper-container clearfix gdlr-core-container" },
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-60 gdlr-core-column-first", "data-skin": "Contact Field", id: "gdlr-core-column-4" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js " },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js ", style: { maxWidth: "760px" } },
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-center-align gdlr-core-title-item-caption-bottom gdlr-core-item-pdlr", style: { paddingBottom: "60px" } },
                                            React.createElement("div", { className: "gdlr-core-title-item-title-wrap " },
                                                React.createElement("h3", { className: "gdlr-core-title-item-title gdlr-core-skin-title  class-test", style: {
                                                        fontSize: "39px",
                                                        fontWeight: 600,
                                                        letterSpacing: "0px",
                                                        textTransform: "none",
                                                    } },
                                                    "Leave us your info",
                                                    " ",
                                                    React.createElement("span", { className: "gdlr-core-title-item-title-divider gdlr-core-skin-divider" }))),
                                            React.createElement("span", { className: "gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption", style: {
                                                    fontSize: "19px",
                                                    fontStyle: "normal",
                                                    letterSpacing: "0px",
                                                } }, "and we will get back to you."))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-contact-form-7-item gdlr-core-item-pdlr gdlr-core-item-pdb " },
                                            React.createElement("div", { role: "form", className: "wpcf7", id: "wpcf7-f1979-p1964-o1", lang: "en-US", dir: "ltr" },
                                                React.createElement("div", { className: "screen-reader-response" },
                                                    React.createElement("p", { role: "status", "aria-live": "polite", "aria-atomic": "true" }),
                                                    " ",
                                                    React.createElement("ul", null)),
                                                React.createElement("form", { action: "https://demo.goodlayers.com/hotale/resort/contact/#wpcf7-f1979-p1964-o1", method: "post", className: "wpcf7-form init", "data-status": "init" },
                                                    React.createElement("div", { style: { display: "none" } },
                                                        React.createElement("input", { type: "hidden", name: "_wpcf7", defaultValue: 1979 }),
                                                        React.createElement("input", { type: "hidden", name: "_wpcf7_version", defaultValue: "5.5.6.1" }),
                                                        React.createElement("input", { type: "hidden", name: "_wpcf7_locale", defaultValue: "en_US" }),
                                                        React.createElement("input", { type: "hidden", name: "_wpcf7_unit_tag", defaultValue: "wpcf7-f1979-p1964-o1" }),
                                                        React.createElement("input", { type: "hidden", name: "_wpcf7_container_post", defaultValue: 1964 }),
                                                        React.createElement("input", { type: "hidden", name: "_wpcf7_posted_data_hash" })),
                                                    React.createElement("div", { className: "gdlr-core-input-wrap gdlr-core-full-width gdlr-core-no-border gdlr-core-with-column" },
                                                        React.createElement("div", { className: "gdlr-core-column-30" },
                                                            React.createElement("span", { className: "wpcf7-form-control-wrap your-name" },
                                                                React.createElement("input", { type: "text", name: "your-name", size: 40, className: "wpcf7-form-control wpcf7-text wpcf7-validates-as-required", "aria-required": "true", "aria-invalid": "false", placeholder: "Full Name*" }))),
                                                        React.createElement("div", { className: "gdlr-core-column-30" },
                                                            React.createElement("span", { className: "wpcf7-form-control-wrap your-email" },
                                                                React.createElement("input", { type: "email", name: "your-email", size: 40, className: "wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email", "aria-required": "true", "aria-invalid": "false", placeholder: "Email*" }))),
                                                        React.createElement("div", { className: "clear" }),
                                                        React.createElement("div", { className: "gdlr-core-column-60" },
                                                            React.createElement("span", { className: "wpcf7-form-control-wrap your-subject" },
                                                                React.createElement("input", { type: "text", name: "your-subject", size: 40, className: "wpcf7-form-control wpcf7-text wpcf7-validates-as-required", "aria-required": "true", "aria-invalid": "false", placeholder: "Subject*" }))),
                                                        React.createElement("div", { className: "clear" }),
                                                        React.createElement("div", { className: "gdlr-core-column-60" },
                                                            React.createElement("span", { className: "wpcf7-form-control-wrap your-message" },
                                                                React.createElement("textarea", { name: "your-message", cols: 40, rows: 10, className: "wpcf7-form-control wpcf7-textarea wpcf7-validates-as-required", "aria-required": "true", "aria-invalid": "false", placeholder: "Message*", defaultValue: "" }))),
                                                        React.createElement("div", { className: "gdlr-core-column-60 gdlr-core-left-align" },
                                                            React.createElement("input", { type: "submit", defaultValue: "Submit Now", className: "wpcf7-form-control has-spinner wpcf7-submit gdlr-core-small-button gdlr-core-curve-button" }),
                                                            React.createElement("span", { className: "wpcf7-spinner" }))),
                                                    React.createElement("div", { className: "wpcf7-response-output", "aria-hidden": "true" }))))))))))),
            ";",
            React.createElement("div", { className: "gdlr-core-pbf-wrapper ", style: { padding: "0px 0px 0px 0px" } },
                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                React.createElement("div", { className: "gdlr-core-pbf-wrapper-content gdlr-core-js " },
                    React.createElement("div", { className: "gdlr-core-pbf-wrapper-container clearfix gdlr-core-pbf-wrapper-full-no-space" },
                        React.createElement("div", { className: "gdlr-core-pbf-element" },
                            React.createElement("div", { className: "gdlr-core-wp-google-map-plugin-item gdlr-core-item-pdlr gdlr-core-item-pdb ", style: { paddingBottom: "0px" } },
                                React.createElement("div", { className: "wpgmp_map_container wpgmp-map-1" },
                                    React.createElement("div", { className: "wpgmp_map_parent" },
                                        React.createElement("div", { className: "wpgmp_map ", style: {
                                                width: "100%",
                                                height: "500px",
                                                position: "relative",
                                                overflow: "hidden",
                                            }, id: "map1" },
                                            React.createElement("div", { style: {
                                                    height: "100%",
                                                    width: "100%",
                                                    position: "absolute",
                                                    top: "0px",
                                                    left: "0px",
                                                    backgroundColor: "rgb(229, 227, 223)",
                                                } },
                                                React.createElement("div", { className: "gm-err-container" },
                                                    React.createElement("div", { className: "gm-err-content" },
                                                        React.createElement("div", { className: "gm-err-icon" },
                                                            React.createElement("img", { src: "https://maps.gstatic.com/mapfiles/api-3/images/icon_error.png", alt: "", draggable: "false", style: { userSelect: "none" } })),
                                                        React.createElement("div", { className: "gm-err-title" }, "Oops! Something went wrong."),
                                                        React.createElement("div", { className: "gm-err-message" }, "This page didn't load Google Maps correctly. See the JavaScript console for technical details."))))))))))))));
    };
    return ContactUs;
}(React.Component));
exports.default = (0, react_redux_1.connect)()(ContactUs);
//# sourceMappingURL=ContactUs.js.map