"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_redux_1 = require("react-redux");
var react_router_dom_1 = require("react-router-dom");
var Header = /** @class */ (function (_super) {
    __extends(Header, _super);
    function Header() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Header.prototype.render = function () {
        return (React.createElement(React.Fragment, null,
            React.createElement("div", { className: "hotale-header-background-transparent" },
                React.createElement("div", { className: "hotale-top-bar " },
                    React.createElement("div", { className: "hotale-top-bar-background" }),
                    React.createElement("div", { className: "hotale-top-bar-container hotale-container " },
                        React.createElement("div", { className: "hotale-top-bar-container-inner clearfix" },
                            React.createElement("div", { className: "hotale-top-bar-left hotale-item-pdlr" },
                                React.createElement("div", { className: "hotale-top-bar-left-text" },
                                    React.createElement("i", { className: "icon-phone", style: { fontSize: '15px', color: '#ffffff', marginRight: '10px' } }),
                                    "1-634-567-34",
                                    React.createElement("i", { className: "icon-envelope", style: { fontSize: '15px', color: '#ffffff', marginLeft: '25px', marginRight: '10px' } }),
                                    "Book@Hotale.co"))))),
                React.createElement("header", { className: "hotale-header-wrap hotale-header-style-plain hotale-style-center-menu hotale-sticky-navigation hotale-style-slide", "data-navigation-offset": 75, style: { display: 'block' } },
                    React.createElement("div", { className: "hotale-header-background" }),
                    React.createElement("div", { className: "hotale-header-container  hotale-container" },
                        React.createElement("div", { className: "hotale-header-container-inner clearfix" },
                            React.createElement("div", { className: "hotale-logo  hotale-item-pdlr" },
                                React.createElement("div", { className: "hotale-logo-inner" },
                                    React.createElement("a", { className: "hotale-fixed-nav-logo", href: "index.html" },
                                        React.createElement("img", { src: "../../../a6e8z9v6.stackpathcdn.com/hotale/resort/wp-content/uploads/sites/2/2022/05/logo-nx1.png", alt: "", width: 147, height: 37, title: "logo-nx1", srcSet: "https://a6e8z9v6.stackpathcdn.com/hotale/resort/wp-content/uploads/sites/2/2022/05/logo-nx1.png 1x, https://a6e8z9v6.stackpathcdn.com/hotale/resort/wp-content/uploads/sites/2/2022/05/logo-nx2-1.png 2x" })),
                                    React.createElement("a", { className: " hotale-orig-logo", href: "index.html" },
                                        React.createElement("img", { src: "../../../a6e8z9v6.stackpathcdn.com/hotale/resort/wp-content/uploads/sites/2/2022/05/logo-nx1.png", alt: "", width: 147, height: 37, title: "logo-nx1", srcSet: "https://a6e8z9v6.stackpathcdn.com/hotale/resort/wp-content/uploads/sites/2/2022/05/logo-nx1.png 1x, https://a6e8z9v6.stackpathcdn.com/hotale/resort/wp-content/uploads/sites/2/2022/05/logo-nx2-1.png 2x" })))),
                            "\t\t\t",
                            React.createElement("div", { className: "hotale-navigation hotale-item-pdlr clearfix " },
                                React.createElement("div", { className: "hotale-main-menu sf-js-enabled sf-arrows", id: "hotale-main-menu", style: { touchAction: 'pan-y' } },
                                    React.createElement("ul", { id: "menu-main-navigation-1", className: "sf-menu" },
                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-14980 current_page_item current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor menu-item-has-children menu-item-15531 hotale-normal-menu" },
                                            React.createElement(react_router_dom_1.Link, { className: "sf-with-ul-pre sf-with-ul", to: "/" }, "Ana S\u0259hif\u0259"),
                                            React.createElement("ul", { className: "sub-menu", style: { display: 'none' } },
                                                React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-14980 current_page_item menu-item-15878", "data-size": 60 },
                                                    React.createElement("a", { href: "index.html" }, "Home \u2013 Resort 1")),
                                                React.createElement("li", { className: "menu-item menu-item-type-custom menu-item-object-custom menu-item-15879", "data-size": 60 },
                                                    React.createElement("a", { target: "_blank", href: "https://demo.goodlayers.com/hotale/resort2/" }, "Home \u2013 Resort 2")),
                                                React.createElement("li", { className: "menu-item menu-item-type-custom menu-item-object-custom menu-item-15877", "data-size": 60 },
                                                    React.createElement("a", { target: "_blank", href: "https://demo.goodlayers.com/hotale/hotel1/" }, "Home \u2013 Hotel 1")),
                                                React.createElement("li", { className: "menu-item menu-item-type-custom menu-item-object-custom menu-item-15880", "data-size": 60 },
                                                    React.createElement("a", { target: "_blank", href: "https://demo.goodlayers.com/hotale/hotel2/" }, "Home \u2013 Hotel 2")),
                                                React.createElement("li", { className: "menu-item menu-item-type-custom menu-item-object-custom menu-item-15881", "data-size": 60 },
                                                    React.createElement("a", { target: "_blank", href: "https://demo.goodlayers.com/hotale/apartment/" }, "Home \u2013 Apartment")),
                                                React.createElement("li", { className: "menu-item menu-item-type-custom menu-item-object-custom menu-item-15876", "data-size": 60 },
                                                    React.createElement("a", { target: "_blank", href: "https://demo.goodlayers.com/hotale/apartment2/" }, "Home \u2013 Apartment 2")))),
                                        React.createElement("li", { className: "menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-15533 hotale-normal-menu" },
                                            React.createElement(react_router_dom_1.Link, { className: "sf-with-ul-pre sf-with-ul", to: "/aboutus" }, "Haqq\u0131m\u0131zda")),
                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-15712 hotale-normal-menu" },
                                            React.createElement(react_router_dom_1.Link, { className: "sf-with-ul-pre sf-with-ul", to: "/rooms" }, "Otaqlar"),
                                            React.createElement("ul", { className: "sub-menu", style: { display: 'none' } },
                                                React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15713", "data-size": 60 },
                                                    React.createElement("a", { href: "room-grid-style-1/index.html" }, "Room Grid Style 1")),
                                                React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15727", "data-size": 60 },
                                                    React.createElement("a", { href: "room-grid-style-2/index.html" }, "Room Grid Style 2")),
                                                React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15726", "data-size": 60 },
                                                    React.createElement("a", { href: "room-grid-style-3/index.html" }, "Room Grid Style 3")),
                                                React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15725", "data-size": 60 },
                                                    React.createElement("a", { href: "room-grid-style-4/index.html" }, "Room Grid Style 4")),
                                                React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15734", "data-size": 60 },
                                                    React.createElement("a", { href: "room-modern-style/index.html" }, "Room Modern Style")),
                                                React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15738", "data-size": 60 },
                                                    React.createElement("a", { href: "room-side-thumbnail/index.html" }, "Room Side Thumbnail")))),
                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-15617 hotale-normal-menu" },
                                            React.createElement(react_router_dom_1.Link, { className: "sf-with-ul-pre sf-with-ul", to: "/blogs" }, "Bloglar"),
                                            React.createElement("ul", { className: "sub-menu", style: { display: 'none' } },
                                                React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-15614", "data-size": 60 },
                                                    React.createElement("a", { href: "blog-3-columns-with-frame/index.html", className: "sf-with-ul-pre sf-with-ul" }, "Blog Columns"),
                                                    React.createElement("ul", { className: "sub-menu", style: { display: 'none' } },
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15594" },
                                                            React.createElement("a", { href: "blog-2-columns/index.html" }, "Blog 2 Columns")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15595" },
                                                            React.createElement("a", { href: "blog-2-columns-with-frame/index.html" }, "Blog 2 Columns With Frame")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15596" },
                                                            React.createElement("a", { href: "blog-3-columns/index.html" }, "Blog 3 Columns")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15598" },
                                                            React.createElement("a", { href: "blog-3-columns-with-frame-post-format/index.html" }, "Blog 3 Columns With Frame / Post Format")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15597" },
                                                            React.createElement("a", { href: "blog-3-columns-with-frame/index.html" }, "Blog 3 Columns With Frame")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15599" },
                                                            React.createElement("a", { href: "blog-4-columns/index.html" }, "Blog 4 Columns")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15600" },
                                                            React.createElement("a", { href: "blog-4-columns-with-frame/index.html" }, "Blog 4 Columns With Frame")))),
                                                React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-15615", "data-size": 60 },
                                                    React.createElement("a", { href: "blog-full-right-sidebar/index.html", className: "sf-with-ul-pre sf-with-ul" }, "Blog Full"),
                                                    React.createElement("ul", { className: "sub-menu", style: { display: 'none' } },
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15605" },
                                                            React.createElement("a", { href: "blog-full-right-sidebar/index.html" }, "Blog Full Right Sidebar")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15606" },
                                                            React.createElement("a", { href: "blog-full-right-sidebar-with-frame/index.html" }, "Blog Full Right Sidebar With Frame")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15603" },
                                                            React.createElement("a", { href: "blog-full-left-sidebar/index.html" }, "Blog Full Left Sidebar")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15604" },
                                                            React.createElement("a", { href: "blog-full-left-sidebar-with-frame/index.html" }, "Blog Full Left Sidebar With Frame")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15601" },
                                                            React.createElement("a", { href: "blog-full-both-sidebar/index.html" }, "Blog Full Both Sidebar")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15602" },
                                                            React.createElement("a", { href: "blog-full-both-sidebar-with-frame/index.html" }, "Blog Full Both Sidebar With Frame")))),
                                                React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-15616", "data-size": 60 },
                                                    React.createElement("a", { href: "blog-grid-3-columns/index.html", className: "sf-with-ul-pre sf-with-ul" }, "Blog Grid"),
                                                    React.createElement("ul", { className: "sub-menu", style: { display: 'none' } },
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15607" },
                                                            React.createElement("a", { href: "blog-grid-2-columns/index.html" }, "Blog Grid 2 Columns")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15608" },
                                                            React.createElement("a", { href: "blog-grid-2-columns-no-space/index.html" }, "Blog Grid 2 Columns No Space")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15609" },
                                                            React.createElement("a", { href: "blog-grid-3-columns/index.html" }, "Blog Grid 3 Columns")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15610" },
                                                            React.createElement("a", { href: "blog-grid-3-columns-no-space/index.html" }, "Blog Grid 3 Columns No Space")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15611" },
                                                            React.createElement("a", { href: "blog-grid-4-columns/index.html" }, "Blog Grid 4 Columns")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-15612" },
                                                            React.createElement("a", { href: "blog-grid-4-columns-no-space/index.html" }, "Blog Grid 4 Columns No Space")))),
                                                React.createElement("li", { className: "menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-15618", "data-size": 60 },
                                                    React.createElement("a", { href: "#", className: "sf-with-ul-pre sf-with-ul" }, "Single Posts"),
                                                    React.createElement("ul", { className: "sub-menu", style: { display: 'none' } },
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-post menu-item-15625" },
                                                            React.createElement("a", { href: "cities-to-visit-for-your-first-time-in-europe/index.html" }, "Just A Post")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-post menu-item-15619" },
                                                            React.createElement("a", { href: "audio-post-format/index.html" }, "Audio Post Format")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-post menu-item-15620" },
                                                            React.createElement("a", { href: "video-post-format/index.html" }, "Video Post Format")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-post menu-item-15621" },
                                                            React.createElement("a", { href: "quote-post-format/index.html" }, "Quote Post Format")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-post menu-item-15623" },
                                                            React.createElement("a", { href: "gallery-post-format/index.html" }, "Gallery Post Format")),
                                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-post menu-item-15624" },
                                                            React.createElement("a", { href: "aside-post-format/index.html" }, "Aside Post Format")))))),
                                        React.createElement("li", { className: "menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-15537 hotale-normal-menu" },
                                            React.createElement(react_router_dom_1.Link, { className: "sf-with-ul-pre sf-with-ul", to: "/contactus" }, "\u018Flaq\u0259"))),
                                    React.createElement("div", { className: "hotale-navigation-slide-bar  hotale-navigation-slide-bar-style-2 hotale-left", "data-size-offset": 0, "data-width": "19px", id: "hotale-navigation-slide-bar", style: { width: '19px', left: '358.313px', display: 'block', overflow: 'hidden' } })),
                                React.createElement("div", { className: "hotale-main-menu-right-wrap clearfix  hotale-item-mglr hotale-navigation-top" },
                                    React.createElement("div", { className: "tourmaster-room-navigation-checkout-wrap " },
                                        React.createElement("a", { id: "tourmaster-room-navigation-checkout-button", className: "tourmaster-room-navigation-checkout-button", href: "room-search/indexae75.html?room_amount=1&room-search=", "data-checkout-label": "Check Out", "data-label": "Book Now" },
                                            "Book Now",
                                            React.createElement("span", { className: "tourmaster-count" }, "0")),
                                        React.createElement("div", { className: "tourmaster-room-cart-item-wrap" },
                                            React.createElement("div", { className: "tourmaster-room-cart-items" },
                                                React.createElement("ul", null),
                                                React.createElement("a", { className: "tourmaster-checkout-button", href: "payment-summary/indexbaa2.html?pt=room&type=cart" }, "Check Out"))))))))))));
    };
    return Header;
}(React.Component));
exports.default = (0, react_redux_1.connect)()(Header);
//# sourceMappingURL=Header.js.map