"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_redux_1 = require("react-redux");
var HomeWelcome = /** @class */ (function (_super) {
    __extends(HomeWelcome, _super);
    function HomeWelcome() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    HomeWelcome.prototype.render = function () {
        return (React.createElement(React.Fragment, null,
            React.createElement("div", { className: "hotale-page-wrapper", id: "hotale-page-wrapper", "data-aos": "fade-bottom", "data-aos-duration": "1000" },
                React.createElement("div", { className: "gdlr-core-page-builder-body" },
                    React.createElement("div", { className: "gdlr-core-pbf-wrapper  gdlr-core-wrapper-full-height gdlr-core-js gdlr-core-full-height-center", style: {
                            margin: "0px",
                            padding: "280px 0px 80px",
                            borderRadius: "20px",
                            minHeight: "308px",
                        }, id: "gdlr-core-wrapper-1", "data-decrease-height": "40px" },
                        React.createElement("div", { className: "gdlr-core-pbf-background-wrap", style: {
                                borderRadius: "20px 20px 20px 20px",
                                MozBorderRadius: "20px 20px 20px 20px",
                                WebkitBorderRadius: "20px 20px 20px 20px",
                            } },
                            React.createElement("div", { className: "gdlr-core-pbf-background gdlr-core-parallax gdlr-core-js", style: {
                                    backgroundImage: "url(".concat(require('../images/home-resort-hero-bg.jpg'), ")"),
                                    backgroundSize: "cover",
                                    backgroundPosition: "center",
                                }, "data-parallax-speed": 0 })),
                        React.createElement("div", { className: "gdlr-core-page-builder-wrapper-top-gradient", style: {
                                height: "344px",
                                opacity: 1,
                                background: "linear-gradient(rgba(0, 0, 0, 100), rgba(0, 0, 0, 0))",
                                //MozBackground: "linear-gradient(rgba(0, 0, 0, 100), rgba(0, 0, 0, 0))",
                                //OBackground: "linear-gradient(rgba(0, 0, 0, 100), rgba(0, 0, 0, 0))",
                                //WebkitBackground: "linear-gradient(rgba(0, 0, 0, 100), rgba(0, 0, 0, 0))",
                                borderRadius: "20px 20px 20px 20px",
                                MozBorderRadius: "20px 20px 20px 20px",
                                WebkitBorderRadius: "20px 20px 20px 20px",
                            } }),
                        React.createElement("div", { className: "gdlr-core-page-builder-wrapper-bottom-gradient", style: {
                                height: "338px",
                                opacity: 1,
                                background: "linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 100))",
                                /*                        MozBackground: "linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 100))",*/
                                /*                        OBackground: "linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 100))",*/
                                /*                        WebkitBackground: "linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 100))",*/
                                borderRadius: "20px 20px 20px 20px",
                                MozBorderRadius: "20px 20px 20px 20px",
                                WebkitBorderRadius: "20px 20px 20px 20px",
                            } }),
                        React.createElement("div", { className: "gdlr-core-pbf-wrapper-content gdlr-core-js  gdlr-core-full-height-content" },
                            React.createElement("div", { className: "gdlr-core-pbf-wrapper-container clearfix gdlr-core-container" },
                                React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-60 gdlr-core-column-first" },
                                    React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js " },
                                        React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js " },
                                            React.createElement("div", { className: "gdlr-core-pbf-element" },
                                                React.createElement("div", { className: "gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-center-align gdlr-core-title-item-caption-bottom gdlr-core-item-pdlr title-rotate", id: "gdlr-core-title-item-1" },
                                                    React.createElement("div", { className: "gdlr-core-title-item-title-wrap " },
                                                        React.createElement("h3", { className: "gdlr-core-title-item-title gdlr-core-skin-title hotale-additional-font class-test", style: {
                                                                fontSize: "126px",
                                                                fontWeight: 400,
                                                                letterSpacing: "0px",
                                                                textTransform: "none",
                                                                color: "#ffffff",
                                                            } },
                                                            "SweetHouse",
                                                            React.createElement("span", { className: "gdlr-core-title-item-title-divider gdlr-core-skin-divider" }))))),
                                            React.createElement("div", { className: "gdlr-core-pbf-element" },
                                                React.createElement("div", { className: "gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align" },
                                                    React.createElement("div", { className: "gdlr-core-text-box-item-content", style: {
                                                            fontSize: "22px",
                                                            fontWeight: 400,
                                                            textTransform: "none",
                                                            color: "#ffffff",
                                                        } },
                                                        React.createElement("p", null, "\u0130stirah\u0259tinizi bizl\u0259 ke\u00E7irin"))))))),
                                React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-60 gdlr-core-column-first", id: "gdlr-core-column-1" },
                                    React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "270px 0px 0px 0px" } },
                                        React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                        React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js " },
                                            React.createElement("div", { className: "gdlr-core-pbf-element" },
                                                React.createElement("div", { className: "tourmaster-room-search-item tourmaster-item-pdlr clearfix" },
                                                    React.createElement("form", { className: "tourmaster-room-search-form tourmaster-radius-round tourmaster-style-box tourmaster-align-horizontal ", action: "https://demo.goodlayers.com/hotale/resort/room-search/", method: "get" },
                                                        React.createElement("div", { className: "tourmaster-room-search-size10" },
                                                            React.createElement("div", { className: "tourmaster-room-date-selection tourmaster-horizontal", "data-avail-date": true },
                                                                React.createElement("div", { className: "tourmaster-custom-start-date gdlr-core-skin-e-background" },
                                                                    React.createElement("div", { className: "tourmaster-head gdlr-core-skin-e-content" }, "Check In"),
                                                                    React.createElement("div", { className: "tourmaster-tail gdlr-core-skin-e-content" }, "Jun 13, 2022"),
                                                                    React.createElement("input", { type: "hidden", name: "start_date", defaultValue: "2022-06-13" })),
                                                                React.createElement("div", { className: "tourmaster-custom-end-date gdlr-core-skin-e-background" },
                                                                    React.createElement("div", { className: "tourmaster-head gdlr-core-skin-e-content" }, "Check Out"),
                                                                    React.createElement("div", { className: "tourmaster-tail gdlr-core-skin-e-content" }, "Jun 14, 2022"),
                                                                    React.createElement("input", { type: "hidden", name: "end_date", defaultValue: "2022-06-14" })),
                                                                React.createElement("div", { className: "tourmaster-custom-datepicker-wrap", "data-date-format": "d M yy" },
                                                                    React.createElement("i", { className: "tourmaster-custom-datepicker-close icon_close" }),
                                                                    React.createElement("div", { className: "tourmaster-custom-datepicker-title" }, "13 Jun 2022 - 14 Jun 2022"),
                                                                    React.createElement("div", { className: "tourmaster-custom-datepicker-calendar hasDatepicker", id: "dp1655140833665" },
                                                                        React.createElement("div", { className: "ui-datepicker-inline ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all ui-datepicker-multi-2 ui-datepicker-multi", style: { width: "34em", display: "block" } },
                                                                            React.createElement("div", { className: "ui-datepicker-group ui-datepicker-group-first" },
                                                                                React.createElement("div", { className: "ui-datepicker-header ui-widget-header ui-helper-clearfix ui-corner-left" },
                                                                                    React.createElement("a", { className: "ui-datepicker-prev ui-corner-all ui-state-disabled", title: "Previous" },
                                                                                        React.createElement("span", { className: "ui-icon ui-icon-circle-triangle-w" }, "Previous")),
                                                                                    React.createElement("div", { className: "ui-datepicker-title" },
                                                                                        React.createElement("select", { className: "ui-datepicker-month", "aria-label": "Select month", "data-handler": "selectMonth", "data-event": "change" },
                                                                                            React.createElement("option", { value: 5 }, "Jun"),
                                                                                            React.createElement("option", { value: 6 }, "Jul"),
                                                                                            React.createElement("option", { value: 7 }, "Aug"),
                                                                                            React.createElement("option", { value: 8 }, "Sep"),
                                                                                            React.createElement("option", { value: 9 }, "Oct"),
                                                                                            React.createElement("option", { value: 10 }, "Nov"),
                                                                                            React.createElement("option", { value: 11 }, "Dec")),
                                                                                        React.createElement("select", { className: "ui-datepicker-year", "aria-label": "Select year", "data-handler": "selectYear", "data-event": "change" },
                                                                                            React.createElement("option", { value: 2022 }, "2022"),
                                                                                            React.createElement("option", { value: 2023 }, "2023"),
                                                                                            React.createElement("option", { value: 2024 }, "2024"),
                                                                                            React.createElement("option", { value: 2025 }, "2025"),
                                                                                            React.createElement("option", { value: 2026 }, "2026"),
                                                                                            React.createElement("option", { value: 2027 }, "2027"),
                                                                                            React.createElement("option", { value: 2028 }, "2028"),
                                                                                            React.createElement("option", { value: 2029 }, "2029"),
                                                                                            React.createElement("option", { value: 2030 }, "2030"),
                                                                                            React.createElement("option", { value: 2031 }, "2031"),
                                                                                            React.createElement("option", { value: 2032 }, "2032")))),
                                                                                React.createElement("table", { className: "ui-datepicker-calendar" },
                                                                                    React.createElement("thead", null,
                                                                                        React.createElement("tr", null,
                                                                                            React.createElement("th", { scope: "col" },
                                                                                                React.createElement("span", { title: "Monday" }, "M")),
                                                                                            React.createElement("th", { scope: "col" },
                                                                                                React.createElement("span", { title: "Tuesday" }, "T")),
                                                                                            React.createElement("th", { scope: "col" },
                                                                                                React.createElement("span", { title: "Wednesday" }, "W")),
                                                                                            React.createElement("th", { scope: "col" },
                                                                                                React.createElement("span", { title: "Thursday" }, "T")),
                                                                                            React.createElement("th", { scope: "col" },
                                                                                                React.createElement("span", { title: "Friday" }, "F")),
                                                                                            React.createElement("th", { scope: "col", className: "ui-datepicker-week-end" },
                                                                                                React.createElement("span", { title: "Saturday" }, "S")),
                                                                                            React.createElement("th", { scope: "col", className: "ui-datepicker-week-end" },
                                                                                                React.createElement("span", { title: "Sunday" }, "S")))),
                                                                                    React.createElement("tbody", null,
                                                                                        React.createElement("tr", null,
                                                                                            React.createElement("td", { className: " ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled" }, "\u00A0"),
                                                                                            React.createElement("td", { className: " ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled" }, "\u00A0"),
                                                                                            React.createElement("td", { className: " ui-datepicker-unselectable ui-state-disabled " },
                                                                                                React.createElement("span", { className: "ui-state-default" }, "1")),
                                                                                            React.createElement("td", { className: " ui-datepicker-unselectable ui-state-disabled " },
                                                                                                React.createElement("span", { className: "ui-state-default" }, "2")),
                                                                                            React.createElement("td", { className: " ui-datepicker-unselectable ui-state-disabled " },
                                                                                                React.createElement("span", { className: "ui-state-default" }, "3")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ui-datepicker-unselectable ui-state-disabled " },
                                                                                                React.createElement("span", { className: "ui-state-default" }, "4")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ui-datepicker-unselectable ui-state-disabled " },
                                                                                                React.createElement("span", { className: "ui-state-default" }, "5"))),
                                                                                        React.createElement("tr", null,
                                                                                            React.createElement("td", { className: " ui-datepicker-unselectable ui-state-disabled " },
                                                                                                React.createElement("span", { className: "ui-state-default" }, "6")),
                                                                                            React.createElement("td", { className: " ui-datepicker-unselectable ui-state-disabled " },
                                                                                                React.createElement("span", { className: "ui-state-default" }, "7")),
                                                                                            React.createElement("td", { className: " ui-datepicker-unselectable ui-state-disabled " },
                                                                                                React.createElement("span", { className: "ui-state-default" }, "8")),
                                                                                            React.createElement("td", { className: " ui-datepicker-unselectable ui-state-disabled " },
                                                                                                React.createElement("span", { className: "ui-state-default" }, "9")),
                                                                                            React.createElement("td", { className: " ui-datepicker-unselectable ui-state-disabled " },
                                                                                                React.createElement("span", { className: "ui-state-default" }, "10")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ui-datepicker-unselectable ui-state-disabled " },
                                                                                                React.createElement("span", { className: "ui-state-default" }, "11")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ui-datepicker-unselectable ui-state-disabled " },
                                                                                                React.createElement("span", { className: "ui-state-default" }, "12"))),
                                                                                        React.createElement("tr", null,
                                                                                            React.createElement("td", { className: " ui-datepicker-days-cell-over tourmaster-start ui-datepicker-current-day ui-datepicker-today", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default ui-state-highlight ui-state-active ui-state-hover", href: "#", "aria-current": "true", "data-date": 13 }, "13")),
                                                                                            React.createElement("td", { className: " tourmaster-end", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 14 }, "14")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 15 }, "15")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 16 }, "16")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 17 }, "17")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 18 }, "18")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 19 }, "19"))),
                                                                                        React.createElement("tr", null,
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 20 }, "20")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 21 }, "21")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 22 }, "22")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 23 }, "23")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 24 }, "24")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 25 }, "25")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 26 }, "26"))),
                                                                                        React.createElement("tr", null,
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 27 }, "27")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 28 }, "28")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 29 }, "29")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 5, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 30 }, "30")),
                                                                                            React.createElement("td", { className: " ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled" }, "\u00A0"),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled" }, "\u00A0"),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled" }, "\u00A0"))))),
                                                                            React.createElement("div", { className: "ui-datepicker-group ui-datepicker-group-last" },
                                                                                React.createElement("div", { className: "ui-datepicker-header ui-widget-header ui-helper-clearfix ui-corner-right" },
                                                                                    React.createElement("a", { className: "ui-datepicker-next ui-corner-all", "data-handler": "next", "data-event": "click", title: "Next" },
                                                                                        React.createElement("span", { className: "ui-icon ui-icon-circle-triangle-e" }, "Next")),
                                                                                    React.createElement("div", { className: "ui-datepicker-title" },
                                                                                        React.createElement("span", { className: "ui-datepicker-month" }, "July"),
                                                                                        "\u00A0",
                                                                                        React.createElement("span", { className: "ui-datepicker-year" }, "2022"))),
                                                                                React.createElement("table", { className: "ui-datepicker-calendar" },
                                                                                    React.createElement("thead", null,
                                                                                        React.createElement("tr", null,
                                                                                            React.createElement("th", { scope: "col" },
                                                                                                React.createElement("span", { title: "Monday" }, "M")),
                                                                                            React.createElement("th", { scope: "col" },
                                                                                                React.createElement("span", { title: "Tuesday" }, "T")),
                                                                                            React.createElement("th", { scope: "col" },
                                                                                                React.createElement("span", { title: "Wednesday" }, "W")),
                                                                                            React.createElement("th", { scope: "col" },
                                                                                                React.createElement("span", { title: "Thursday" }, "T")),
                                                                                            React.createElement("th", { scope: "col" },
                                                                                                React.createElement("span", { title: "Friday" }, "F")),
                                                                                            React.createElement("th", { scope: "col", className: "ui-datepicker-week-end" },
                                                                                                React.createElement("span", { title: "Saturday" }, "S")),
                                                                                            React.createElement("th", { scope: "col", className: "ui-datepicker-week-end" },
                                                                                                React.createElement("span", { title: "Sunday" }, "S")))),
                                                                                    React.createElement("tbody", null,
                                                                                        React.createElement("tr", null,
                                                                                            React.createElement("td", { className: " ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled" }, "\u00A0"),
                                                                                            React.createElement("td", { className: " ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled" }, "\u00A0"),
                                                                                            React.createElement("td", { className: " ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled" }, "\u00A0"),
                                                                                            React.createElement("td", { className: " ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled" }, "\u00A0"),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 1 }, "1")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 2 }, "2")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 3 }, "3"))),
                                                                                        React.createElement("tr", null,
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 4 }, "4")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 5 }, "5")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 6 }, "6")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 7 }, "7")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 8 }, "8")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 9 }, "9")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 10 }, "10"))),
                                                                                        React.createElement("tr", null,
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 11 }, "11")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 12 }, "12")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 13 }, "13")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 14 }, "14")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 15 }, "15")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 16 }, "16")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 17 }, "17"))),
                                                                                        React.createElement("tr", null,
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 18 }, "18")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 19 }, "19")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 20 }, "20")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 21 }, "21")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 22 }, "22")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 23 }, "23")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 24 }, "24"))),
                                                                                        React.createElement("tr", null,
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 25 }, "25")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 26 }, "26")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 27 }, "27")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 28 }, "28")),
                                                                                            React.createElement("td", { className: " ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 29 }, "29")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 30 }, "30")),
                                                                                            React.createElement("td", { className: " ui-datepicker-week-end ", "data-handler": "selectDay", "data-event": "click", "data-month": 6, "data-year": 2022 },
                                                                                                React.createElement("a", { className: "ui-state-default", href: "#", "aria-current": "false", "data-date": 31 }, "31")))))),
                                                                            React.createElement("div", { className: "ui-datepicker-row-break" })))))),
                                                        React.createElement("div", { className: "tourmaster-room-size2" },
                                                            React.createElement("div", { className: "tourmaster-room-amount-selection " },
                                                                React.createElement("div", { className: "tourmaster-custom-amount-display gdlr-core-skin-e-background" },
                                                                    React.createElement("div", { className: "tourmaster-head gdlr-core-skin-e-content" }, "Room"),
                                                                    React.createElement("div", { className: "tourmaster-tail gdlr-core-skin-e-content" },
                                                                        React.createElement("span", { className: "tourmaster-space" }),
                                                                        "1")),
                                                                React.createElement("div", { className: "tourmaster-custom-amount-selection-wrap" },
                                                                    React.createElement("div", { className: "tourmaster-custom-amount-selection-item clearfix" },
                                                                        React.createElement("div", { className: "tourmaster-head" }, "Room"),
                                                                        React.createElement("div", { className: "tourmaster-tail" },
                                                                            React.createElement("span", { className: "tourmaster-minus" },
                                                                                React.createElement("i", { className: "icon_minus-06" })),
                                                                            React.createElement("span", { className: "tourmaster-amount" }, "1"),
                                                                            React.createElement("span", { className: "tourmaster-plus" },
                                                                                React.createElement("i", { className: "icon_plus" }))),
                                                                        React.createElement("input", { type: "hidden", name: "room_amount", defaultValue: 1 }))))),
                                                        React.createElement("div", { className: "tourmaster-room-search-size5" },
                                                            React.createElement("div", { className: "tourmaster-room-amount-selection " },
                                                                React.createElement("div", { className: "tourmaster-custom-amount-display gdlr-core-skin-e-background" },
                                                                    React.createElement("div", { className: "tourmaster-head gdlr-core-skin-e-content" }, "Guests"),
                                                                    React.createElement("div", { className: "tourmaster-tail gdlr-core-skin-e-content" },
                                                                        React.createElement("span", { className: "tourmaster-space" }),
                                                                        "Adults 2",
                                                                        React.createElement("span", { className: "tourmaster-space" }),
                                                                        "Children 0")),
                                                                React.createElement("div", { className: "tourmaster-custom-amount-selection-wrap" },
                                                                    React.createElement("div", { className: "tourmaster-custom-amount-selection-item clearfix", "data-label": "Adults" },
                                                                        React.createElement("div", { className: "tourmaster-head" }, "Adults"),
                                                                        React.createElement("div", { className: "tourmaster-tail" },
                                                                            React.createElement("span", { className: "tourmaster-minus" },
                                                                                React.createElement("i", { className: "icon_minus-06" })),
                                                                            React.createElement("span", { className: "tourmaster-amount" }, "2"),
                                                                            React.createElement("span", { className: "tourmaster-plus" },
                                                                                React.createElement("i", { className: "icon_plus" }))),
                                                                        React.createElement("input", { type: "hidden", name: "adult", defaultValue: 2 })),
                                                                    React.createElement("div", { className: "tourmaster-custom-amount-selection-item clearfix", "data-label": "Children" },
                                                                        React.createElement("div", { className: "tourmaster-head" }, "Children"),
                                                                        React.createElement("div", { className: "tourmaster-tail" },
                                                                            React.createElement("span", { className: "tourmaster-minus" },
                                                                                React.createElement("i", { className: "icon_minus-06" })),
                                                                            React.createElement("span", { className: "tourmaster-amount" }, "0"),
                                                                            React.createElement("span", { className: "tourmaster-plus" },
                                                                                React.createElement("i", { className: "icon_plus" }))),
                                                                        React.createElement("input", { type: "hidden", name: "children", defaultValue: 0 }))))),
                                                        React.createElement("div", { className: "tourmaster-room-search-size4 tourmaster-room-search-submit-wrap" },
                                                            React.createElement("input", { className: "tourmaster-room-search-submit tourmaster-style-border", type: "submit", defaultValue: "Search Room", style: {
                                                                    background: "#ffffff",
                                                                    color: "#ffffff",
                                                                    borderColor: "#ffffff",
                                                                } })),
                                                        React.createElement("input", { type: "hidden", name: "room-search" }))))))))))))));
    };
    return HomeWelcome;
}(React.Component));
exports.default = (0, react_redux_1.connect)()(HomeWelcome);
//# sourceMappingURL=HomeWelcome.js.map