"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_redux_1 = require("react-redux");
var HomeFacilities = /** @class */ (function (_super) {
    __extends(HomeFacilities, _super);
    function HomeFacilities() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    HomeFacilities.prototype.render = function () {
        return (React.createElement(React.Fragment, null,
            React.createElement("div", { className: "gdlr-core-pbf-wrapper", style: { padding: "50px 0px 200px 0px" }, id: "gdlr-core-wrapper-4", "data-aos": "zoom-out-right", "data-aos-duration": "2000" },
                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                React.createElement("div", { className: "gdlr-core-pbf-background-wrap", style: { top: "-70px" } },
                    React.createElement("div", { className: "gdlr-core-pbf-background gdlr-core-parallax gdlr-core-js", style: {
                            backgroundImage: "url(".concat(require('../images/Group-36.jpg'), ")"),
                            backgroundRepeat: "no-repeat",
                            backgroundPosition: "top center",
                        }, "data-parallax-speed": 0 })),
                React.createElement("div", { className: "gdlr-core-pbf-wrapper-content gdlr-core-js " },
                    React.createElement("div", { className: "gdlr-core-pbf-wrapper-container clearfix gdlr-core-container-custom", style: { maxWidth: "1000px" } },
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-60 gdlr-core-column-first" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js " },
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js " },
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-center-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr", id: "gdlr-core-title-item-3" },
                                            React.createElement("div", { className: "gdlr-core-title-item-title-wrap " },
                                                React.createElement("h3", { className: "gdlr-core-title-item-title gdlr-core-skin-title hotale-additional-font class-test", style: {
                                                        fontSize: "80px",
                                                        fontWeight: 400,
                                                        letterSpacing: "0px",
                                                        textTransform: "none",
                                                        color: "#000000",
                                                    } },
                                                    "Xidm\u0259tl\u0259r\u0259 daxildir.",
                                                    React.createElement("span", { className: "gdlr-core-title-item-title-divider gdlr-core-skin-divider" })))))))),
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-60 gdlr-core-column-first", id: "gdlr-core-column-8" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "0px 0px 30px 0px" } },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js ", style: { maxWidth: "760px" } },
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align gdlr-core-no-p-space", style: { paddingBottom: "0px" } },
                                            React.createElement("div", { className: "gdlr-core-text-box-item-content", style: {
                                                    fontSize: "21px",
                                                    fontWeight: 400,
                                                    letterSpacing: "0px",
                                                    textTransform: "none",
                                                    color: "#898989",
                                                } },
                                                React.createElement("p", null, "Tam funksyonal v\u0259 daima yenil\u0259n\u0259n xidm\u0259tl\u0259r d\u00FC\u015F\u0259rg\u0259si il\u0259 istifad\u0259\u00E7il\u0259ri m\u0259mnun edirik."))))))),
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-12 gdlr-core-column-first", id: "gdlr-core-column-9" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "70px 0px 0px 0px" } },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js", "data-gdlr-animation-duration": "600ms", "data-gdlr-animation-offset": "0.8", style: {} },
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-image-item gdlr-core-item-pdb  gdlr-core-center-align gdlr-core-item-pdlr" },
                                            React.createElement("div", { className: "gdlr-core-image-item-wrap gdlr-core-media-image  gdlr-core-image-item-style-rectangle", style: { borderWidth: "0px", maxWidth: "65px" } },
                                                React.createElement("img", { src: require('../images/Group-40.png'), alt: "", width: 130, height: 110, title: "Group 40" })))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-center-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr", style: { paddingBottom: "0px" } },
                                            React.createElement("div", { className: "gdlr-core-title-item-title-wrap " },
                                                React.createElement("h3", { className: "gdlr-core-title-item-title gdlr-core-skin-title  class-test", style: {
                                                        fontSize: "20px",
                                                        fontWeight: 500,
                                                        letterSpacing: "0px",
                                                        textTransform: "none",
                                                        color: "#000000",
                                                    } },
                                                    "Parking",
                                                    React.createElement("span", { className: "gdlr-core-title-item-title-divider gdlr-core-skin-divider" })))))))),
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-12", id: "gdlr-core-column-10" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "70px 0px 0px 0px" } },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js", "data-gdlr-animation-duration": "600ms", "data-gdlr-animation-offset": "0.8", style: {} },
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-icon-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align" },
                                            React.createElement("i", { className: " gdlr-core-icon-item-icon gdlr-icon-safe-box1", style: {
                                                    color: "#212121",
                                                    fontSize: "62px",
                                                    minWidth: "62px",
                                                    minHeight: "62px",
                                                } }))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-center-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr", style: { paddingBottom: "0px" } },
                                            React.createElement("div", { className: "gdlr-core-title-item-title-wrap " },
                                                React.createElement("h3", { className: "gdlr-core-title-item-title gdlr-core-skin-title  class-test", style: {
                                                        fontSize: "20px",
                                                        fontWeight: 500,
                                                        letterSpacing: "0px",
                                                        textTransform: "none",
                                                        color: "#000000",
                                                    } },
                                                    "Seyf",
                                                    React.createElement("span", { className: "gdlr-core-title-item-title-divider gdlr-core-skin-divider" })))))))),
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-12", id: "gdlr-core-column-11" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "70px 0px 0px 0px" } },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js", "data-gdlr-animation-duration": "600ms", "data-gdlr-animation-offset": "0.8", style: {} },
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-icon-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align" },
                                            React.createElement("i", { className: " gdlr-core-icon-item-icon gdlr-icon-swimming-pool1", style: {
                                                    color: "#212121",
                                                    fontSize: "62px",
                                                    minWidth: "62px",
                                                    minHeight: "62px",
                                                } }))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-center-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr", style: { paddingBottom: "0px" } },
                                            React.createElement("div", { className: "gdlr-core-title-item-title-wrap " },
                                                React.createElement("h3", { className: "gdlr-core-title-item-title gdlr-core-skin-title  class-test", style: {
                                                        fontSize: "20px",
                                                        fontWeight: 500,
                                                        letterSpacing: "0px",
                                                        textTransform: "none",
                                                        color: "#000000",
                                                    } },
                                                    "Hovuz",
                                                    React.createElement("span", { className: "gdlr-core-title-item-title-divider gdlr-core-skin-divider" })))))))),
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-12", id: "gdlr-core-column-12" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "70px 0px 0px 0px" } },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js", "data-gdlr-animation-duration": "600ms", "data-gdlr-animation-offset": "0.8", style: {} },
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-icon-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align" },
                                            React.createElement("i", { className: " gdlr-core-icon-item-icon gdlr-icon-massage", style: {
                                                    color: "#212121",
                                                    fontSize: "62px",
                                                    minWidth: "62px",
                                                    minHeight: "62px",
                                                } }))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-center-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr", style: { paddingBottom: "0px" } },
                                            React.createElement("div", { className: "gdlr-core-title-item-title-wrap " },
                                                React.createElement("h3", { className: "gdlr-core-title-item-title gdlr-core-skin-title  class-test", style: {
                                                        fontSize: "20px",
                                                        fontWeight: 500,
                                                        letterSpacing: "0px",
                                                        textTransform: "none",
                                                        color: "#000000",
                                                    } },
                                                    "Spa",
                                                    React.createElement("span", { className: "gdlr-core-title-item-title-divider gdlr-core-skin-divider" })))))))),
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-12", id: "gdlr-core-column-13" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "70px 0px 0px 0px" } },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js", "data-gdlr-animation-duration": "600ms", "data-gdlr-animation-offset": "0.8", style: {} },
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-icon-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align" },
                                            React.createElement("i", { className: " gdlr-core-icon-item-icon gdlr-icon-weights", style: {
                                                    color: "#212121",
                                                    fontSize: "64px",
                                                    minWidth: "64px",
                                                    minHeight: "64px",
                                                } }))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-center-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr", style: { paddingBottom: "0px" } },
                                            React.createElement("div", { className: "gdlr-core-title-item-title-wrap " },
                                                React.createElement("h3", { className: "gdlr-core-title-item-title gdlr-core-skin-title  class-test", style: {
                                                        fontSize: "20px",
                                                        fontWeight: 500,
                                                        letterSpacing: "0px",
                                                        textTransform: "none",
                                                        color: "#000000",
                                                    } },
                                                    "\u0130dman zal\u0131",
                                                    React.createElement("span", { className: "gdlr-core-title-item-title-divider gdlr-core-skin-divider" })))))))),
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-12 gdlr-core-column-first", id: "gdlr-core-column-14" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "0px 0px 0px 0px" } },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js " }))),
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-12", id: "gdlr-core-column-15" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "75px 0px 0px 0px" } },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js", "data-gdlr-animation-duration": "600ms", "data-gdlr-animation-offset": "0.8", style: {} },
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-icon-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align" },
                                            React.createElement("i", { className: " gdlr-core-icon-item-icon gdlr-icon-wifi-signal", style: {
                                                    color: "#212121",
                                                    fontSize: "65px",
                                                    minWidth: "65px",
                                                    minHeight: "65px",
                                                } }))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-center-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr", style: { paddingBottom: "0px" } },
                                            React.createElement("div", { className: "gdlr-core-title-item-title-wrap " },
                                                React.createElement("h3", { className: "gdlr-core-title-item-title gdlr-core-skin-title  class-test", style: {
                                                        fontSize: "20px",
                                                        fontWeight: 500,
                                                        letterSpacing: "0px",
                                                        textTransform: "none",
                                                        color: "#000000",
                                                    } },
                                                    "Wifi",
                                                    React.createElement("span", { className: "gdlr-core-title-item-title-divider gdlr-core-skin-divider" })))))))),
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-12", id: "gdlr-core-column-16" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "75px 0px 0px 0px" } },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js", "data-gdlr-animation-duration": "600ms", "data-gdlr-animation-offset": "0.8", style: {} },
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-icon-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align" },
                                            React.createElement("i", { className: " gdlr-core-icon-item-icon gdlr-icon-breakfast", style: {
                                                    color: "#212121",
                                                    fontSize: "65px",
                                                    minWidth: "65px",
                                                    minHeight: "65px",
                                                } }))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-center-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr", style: { paddingBottom: "0px" } },
                                            React.createElement("div", { className: "gdlr-core-title-item-title-wrap " },
                                                React.createElement("h3", { className: "gdlr-core-title-item-title gdlr-core-skin-title  class-test", style: {
                                                        fontSize: "20px",
                                                        fontWeight: 500,
                                                        letterSpacing: "0px",
                                                        textTransform: "none",
                                                        color: "#000000",
                                                    } },
                                                    "S\u0259h\u0259r Yem\u0259yi",
                                                    React.createElement("span", { className: "gdlr-core-title-item-title-divider gdlr-core-skin-divider" })))))))),
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-12", id: "gdlr-core-column-17" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "73px 0px 0px 0px" } },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js", "data-gdlr-animation-duration": "600ms", "data-gdlr-animation-offset": "0.8", style: {} },
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-icon-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-center-align" },
                                            React.createElement("i", { className: " gdlr-core-icon-item-icon gdlr-icon-workspace", style: {
                                                    color: "#212121",
                                                    fontSize: "67px",
                                                    minWidth: "67px",
                                                    minHeight: "67px",
                                                } }))),
                                    React.createElement("div", { className: "gdlr-core-pbf-element" },
                                        React.createElement("div", { className: "gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-center-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr", style: { paddingBottom: "0px" } },
                                            React.createElement("div", { className: "gdlr-core-title-item-title-wrap " },
                                                React.createElement("h3", { className: "gdlr-core-title-item-title gdlr-core-skin-title  class-test", style: {
                                                        fontSize: "20px",
                                                        fontWeight: 500,
                                                        letterSpacing: "0px",
                                                        textTransform: "none",
                                                        color: "#000000",
                                                    } },
                                                    "\u0130\u015F m\u00FChiti",
                                                    React.createElement("span", { className: "gdlr-core-title-item-title-divider gdlr-core-skin-divider" })))))))),
                        React.createElement("div", { className: "gdlr-core-pbf-column gdlr-core-column-12", id: "gdlr-core-column-18" },
                            React.createElement("div", { className: "gdlr-core-pbf-column-content-margin gdlr-core-js ", style: { padding: "70px 0px 0px 0px" } },
                                React.createElement("div", { className: "gdlr-core-pbf-background-wrap" }),
                                React.createElement("div", { className: "gdlr-core-pbf-column-content clearfix gdlr-core-js " })))))),
            ";"));
    };
    return HomeFacilities;
}(React.Component));
exports.default = (0, react_redux_1.connect)()(HomeFacilities);
//# sourceMappingURL=HomeFacilities.js.map